### ISSUE TITLE
Parsing fails with negative value in numerical questions

### ISSUE THREAD

**Issue by dullin** [ethan-ou/vscode-gift#15]
When using a numerical question, having a negative value is considered an error where it shouldn't be.

Here is an example:

```gift
Write the value -1{#-1}
```

**Comment by dullin** [comment]
This is probably related to the parser (where the error is also present). I opened an issue upstream.

fuhrmanator/GIFT-grammar-PEG.js#55

**Comment by ethan-ou** [comment]
The newest version of the extensions now has the fix merged in. Have a go and see if it's working for you.
