### ISSUE TITLE
.txt files should not be GIFT format by default

### ISSUE THREAD

**Issue by fuhrmanator** [ethan-ou/vscode-gift#8]
I'm editing a .txt file (in a context that is not GIFT) but I can't seem to get VSCode to *not* see it as GIFT. I don't think the extension should assume .txt is GIFT format. Furthermore, I can't find a way to "turn off" the GIFT mode in the .txt file. It shows up as having lots of errors (problems), which would be right if it were a GIFT file (but it's not).

**Comment by ethan-ou** [comment]
I've actually been checking this for a couple of days now. Sorry for the late reply. I can't seem to wrap my head around why the extension is enabled on languages like this.

I'm thinking the issue might be that when selecting GIFT then switching back to plain text the extension keeps running. I'm researching how to resolve this.

**Comment by ethan-ou** [comment]
Okay so there were two issues that were compounding together when using the extension:
1. GIFT was the default language when opening a plain text document. I'll remove that.
2. The errors from GIFT weren't being cleared when you changed languages from GIFT to plain text. That's been resolved.

The next update should come out now which will resolve this issue. Give it a shot when you can.
